language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2

before_install:
  - gem update bundler && bundle --version

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

matrix:
  exclude:
    - rvm: rbx
      gemfile: gemfiles/4.0.gemfile
  include:
    - rvm: 2.2.2
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/5.0.gemfile
